import { Manrope } from "next/font/google";
import "./styles/globals.scss";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-manrope", // optional but recommended
  display: "swap",
});
export const metadata = {
  title: "Client Leaf",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} `}>
        {children}
      </body>
    </html>
  );
}
